import { useMemo } from 'react'
import { differenceInYears } from 'date-fns'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { useLivePhases } from '@/hooks/useLiveData'
import type { FamilyMember } from '@/types'

interface FamilyMemberListProps {
  members: FamilyMember[]
  scenarioId: string
  onEdit: (member: FamilyMember) => void
  onDelete: (memberId: string) => void
}

const RELATIONSHIP_LABELS: Record<string, string> = {
  parent: 'Parent',
  'parent-in-law': 'In-law',
  spouse: 'Spouse',
  child: 'Child',
  sibling: 'Sibling',
}

const RELATIONSHIP_COLORS: Record<string, string> = {
  parent: 'bg-blue-100 text-blue-800',
  'parent-in-law': 'bg-indigo-100 text-indigo-800',
  spouse: 'bg-pink-100 text-pink-800',
  child: 'bg-green-100 text-green-800',
  sibling: 'bg-amber-100 text-amber-800',
}

export function FamilyMemberList({ members, scenarioId, onEdit, onDelete }: FamilyMemberListProps) {
  const phases = useLivePhases(scenarioId)

  const autoPhaseCountByMember = useMemo(() => {
    if (!phases) return {}
    const counts: Record<string, number> = {}
    for (const p of phases) {
      if (p.autoGenerated && p.familyMemberId) {
        counts[p.familyMemberId] = (counts[p.familyMemberId] ?? 0) + 1
      }
    }
    return counts
  }, [phases])

  if (members.length === 0) {
    return (
      <p className="text-xs text-muted-foreground text-center py-4">
        No family members added yet.
      </p>
    )
  }

  return (
    <div className="space-y-2">
      {members.map((m) => {
        const age = differenceInYears(new Date(), new Date(m.birthDate))
        const phaseCount = autoPhaseCountByMember[m.id] ?? 0

        return (
          <Card key={m.id}>
            <CardContent className="p-3 flex items-center gap-3">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <span className="font-medium text-sm truncate">{m.name}</span>
                  <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-semibold ${RELATIONSHIP_COLORS[m.relationship] ?? ''}`}>
                    {RELATIONSHIP_LABELS[m.relationship] ?? m.relationship}
                  </span>
                </div>
                <div className="text-xs text-muted-foreground mt-0.5">
                  Age {age} &middot; {m.sex} &middot; {phaseCount} auto-generated phase{phaseCount !== 1 ? 's' : ''}
                </div>
              </div>
              <div className="flex gap-1 shrink-0">
                <Button size="sm" variant="outline" className="h-7 px-2 text-xs" onClick={() => onEdit(m)}>
                  Edit
                </Button>
                <Button size="sm" variant="outline" className="h-7 px-2 text-xs text-destructive" onClick={() => onDelete(m.id)}>
                  Del
                </Button>
              </div>
            </CardContent>
          </Card>
        )
      })}
    </div>
  )
}
