import { describe, it, expect } from 'vitest'
import { generateFamilyPhases } from '../family-phase-engine'
import type { FamilyMember } from '@/types'

function makeMember(overrides: Partial<FamilyMember> = {}): FamilyMember {
  return {
    id: 'fm-1',
    personId: 'p-1',
    name: 'Test Member',
    birthDate: '1955-06-15',
    sex: 'female',
    relationship: 'parent',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
    ...overrides,
  }
}

describe('family-phase-engine', () => {
  it('generates 3 caregiving phases for an elderly parent', () => {
    const member = makeMember({ relationship: 'parent', sex: 'female', birthDate: '1955-06-15' })
    const phases = generateFamilyPhases(member, '1990-01-01')

    expect(phases.length).toBe(3)
    expect(phases.every((p) => p.category === 'caregiving')).toBe(true)
    expect(phases.every((p) => p.autoGenerated === true)).toBe(true)
    expect(phases.every((p) => p.familyMemberId === 'fm-1')).toBe(true)

    // Phases should be chronologically ordered (light → moderate → full)
    const startDates = phases.map((p) => new Date(p.startDate).getTime())
    for (let i = 1; i < startDates.length; i++) {
      expect(startDates[i]).toBeGreaterThanOrEqual(startDates[i - 1])
    }
  })

  it('produces different onset timing for male vs female parents', () => {
    const female = makeMember({ sex: 'female', birthDate: '1955-01-01' })
    const male = makeMember({ sex: 'male', birthDate: '1955-01-01' })

    const femalePhases = generateFamilyPhases(female, '1990-01-01')
    const malePhases = generateFamilyPhases(male, '1990-01-01')

    // Both should have phases
    expect(femalePhases.length).toBeGreaterThan(0)
    expect(malePhases.length).toBeGreaterThan(0)

    // Onset timing may differ due to gender factor in care curve
    const femaleStart = new Date(femalePhases[0].startDate).getTime()
    const maleStart = new Date(malePhases[0].startDate).getTime()
    // Females generally have earlier care onset due to higher disability factor
    expect(femaleStart).not.toBe(maleStart)
  })

  it('generates child development phases, skipping past ones for older children', () => {
    // A newborn should get all 6 phases
    const baby = makeMember({
      relationship: 'child',
      birthDate: '2025-06-01',
      name: 'Baby',
    })
    const babyPhases = generateFamilyPhases(baby, '1990-01-01')
    expect(babyPhases.length).toBe(6)
    expect(babyPhases.every((p) => p.category === 'family')).toBe(true)

    // A 12-year-old should skip infant, toddler, preschool, elementary — keep middle school, high school
    const teen = makeMember({
      relationship: 'child',
      birthDate: '2014-01-01',
      name: 'Teen',
    })
    const teenPhases = generateFamilyPhases(teen, '1990-01-01')
    expect(teenPhases.length).toBe(2) // Middle School (ends 13) + High School (ends 18)
    expect(teenPhases[0].name).toContain('Middle School')
    expect(teenPhases[1].name).toContain('High School')
  })

  it('dispatches correctly: parent → caregiving, child → family, sibling → empty', () => {
    const parent = makeMember({ relationship: 'parent' })
    const child = makeMember({ relationship: 'child', birthDate: '2024-01-01' })
    const sibling = makeMember({ relationship: 'sibling' })

    const parentPhases = generateFamilyPhases(parent, '1990-01-01')
    const childPhases = generateFamilyPhases(child, '1990-01-01')
    const siblingPhases = generateFamilyPhases(sibling, '1990-01-01')

    expect(parentPhases.every((p) => p.category === 'caregiving')).toBe(true)
    expect(childPhases.every((p) => p.category === 'family')).toBe(true)
    expect(siblingPhases).toEqual([])
  })

  it('spouse gets 0.7x caregiving hours compared to parent', () => {
    const parent = makeMember({ relationship: 'parent', sex: 'male', birthDate: '1955-01-01' })
    const spouse = makeMember({ relationship: 'spouse', sex: 'male', birthDate: '1955-01-01' })

    const parentPhases = generateFamilyPhases(parent, '1990-01-01')
    const spousePhases = generateFamilyPhases(spouse, '1990-01-01')

    // Both should have same number of phases
    expect(spousePhases.length).toBe(parentPhases.length)

    // Spouse caregiving hours should be less (0.7x)
    for (let i = 0; i < parentPhases.length; i++) {
      expect(spousePhases[i].caregivingHours).toBeLessThan(parentPhases[i].caregivingHours)
    }
  })

  it('all generated phases have required autoGenerated and familyMemberId fields', () => {
    const member = makeMember({ id: 'fm-test', relationship: 'parent' })
    const phases = generateFamilyPhases(member, '1990-01-01')

    for (const phase of phases) {
      expect(phase.autoGenerated).toBe(true)
      expect(phase.familyMemberId).toBe('fm-test')
      expect(phase.startDate).toBeTruthy()
      expect(phase.endDate).toBeTruthy()
      expect(new Date(phase.startDate).getTime()).toBeLessThan(new Date(phase.endDate).getTime())
    }
  })
})
