import { describe, it, expect } from 'vitest'
import {
  dateToPixel,
  pixelToDate,
  getPhaseLayout,
  getVisiblePhases,
  getAxisTicks,
  clampPixelsPerDay,
} from '../timeline-engine'
import { PhaseCategory, CertaintyLevel, FlexibilityLevel } from '@/types'
import type { Phase } from '@/types'

const origin = new Date('2024-01-01')

function makePhase(overrides: Partial<Phase> = {}): Phase {
  return {
    id: 'p1',
    scenarioId: 's1',
    name: 'Test Phase',
    category: PhaseCategory.Career,
    startDate: '2024-06-01',
    endDate: '2025-06-01',
    certainty: CertaintyLevel.Confirmed,
    flexibility: FlexibilityLevel.Fixed,
    loadTimeCost: 50,
    emotionalIntensity: 30,
    caregivingHours: 0,
    notes: '',
    order: 0,
    createdAt: '',
    updatedAt: '',
    ...overrides,
  }
}

describe('dateToPixel / pixelToDate', () => {
  it('converts date to pixel correctly', () => {
    const date = new Date('2024-07-01')
    const ppd = 1
    const px = dateToPixel(date, origin, ppd)
    // Jan 1 to Jul 1 = 182 days
    expect(px).toBe(182)
  })

  it('round-trips correctly', () => {
    const ppd = 2
    const px = 364
    const date = pixelToDate(px, origin, ppd)
    const backPx = dateToPixel(date, origin, ppd)
    expect(backPx).toBe(px)
  })
})

describe('getPhaseLayout', () => {
  it('assigns rows by category for regular phases', () => {
    const phases = [
      makePhase({ id: 'p1', category: PhaseCategory.Career }),
      makePhase({ id: 'p2', category: PhaseCategory.Family, startDate: '2024-03-01', endDate: '2025-03-01' }),
    ]
    const result = getPhaseLayout(phases, origin, 1)
    expect(result.regularLayouts).toHaveLength(2)
    expect(result.regularLayouts[0].row).not.toBe(result.regularLayouts[1].row)
  })

  it('computes positive width', () => {
    const result = getPhaseLayout([makePhase()], origin, 1)
    expect(result.regularLayouts[0].width).toBeGreaterThan(0)
  })

  it('separates auto-generated family phases into family layouts', () => {
    const phases = [
      makePhase({ id: 'p1', category: PhaseCategory.Career }),
      makePhase({
        id: 'p2',
        category: PhaseCategory.Caregiving,
        autoGenerated: true,
        familyMemberId: 'fm-1',
        name: 'Mom — Light Care',
        caregivingHours: 5,
      }),
      makePhase({
        id: 'p3',
        category: PhaseCategory.Caregiving,
        autoGenerated: true,
        familyMemberId: 'fm-1',
        name: 'Mom — Full Care',
        caregivingHours: 30,
      }),
    ]
    const result = getPhaseLayout(phases, origin, 1)
    expect(result.regularLayouts).toHaveLength(1)
    expect(result.familyLayouts).toHaveLength(2)
    expect(result.familyLanes).toHaveLength(1)
    expect(result.familyLanes[0].label).toBe('Mom')
  })

  it('scales band height with caregiving hours', () => {
    const phases = [
      makePhase({
        id: 'p1', autoGenerated: true, familyMemberId: 'fm-1',
        caregivingHours: 5, category: PhaseCategory.Caregiving,
      }),
      makePhase({
        id: 'p2', autoGenerated: true, familyMemberId: 'fm-1',
        caregivingHours: 30, category: PhaseCategory.Caregiving,
      }),
    ]
    const result = getPhaseLayout(phases, origin, 1)
    const light = result.familyLayouts.find((l) => l.phase.id === 'p1')!
    const full = result.familyLayouts.find((l) => l.phase.id === 'p2')!
    expect(full.bandHeight).toBeGreaterThan(light.bandHeight)
    expect(light.bandHeight).toBeGreaterThanOrEqual(12) // MIN_BAND_HEIGHT
    expect(full.bandHeight).toBeLessThanOrEqual(44) // MAX_BAND_HEIGHT
  })
})

describe('getVisiblePhases', () => {
  it('filters out off-screen phases', () => {
    const result = getPhaseLayout(
      [
        makePhase({ id: 'p1', startDate: '2024-06-01', endDate: '2025-06-01' }),
        makePhase({ id: 'p2', startDate: '2030-01-01', endDate: '2031-01-01' }),
      ],
      origin,
      1,
    )
    const visible = getVisiblePhases(result.regularLayouts, { offsetX: 0, offsetY: 0, pixelsPerDay: 1 }, 600)
    // Only the first phase should be visible (within first 600px = 600 days from origin)
    expect(visible.length).toBe(1)
    expect(visible[0].phase.id).toBe('p1')
  })
})

describe('getAxisTicks', () => {
  it('returns ticks for year view', () => {
    const ticks = getAxisTicks(origin, { offsetX: 0, offsetY: 0, pixelsPerDay: 1 }, 800)
    expect(ticks.length).toBeGreaterThan(0)
    expect(ticks.some((t) => t.isMajor)).toBe(true)
  })
})

describe('clampPixelsPerDay', () => {
  it('clamps to min', () => {
    expect(clampPixelsPerDay(0.001)).toBe(0.01)
  })

  it('clamps to max', () => {
    expect(clampPixelsPerDay(200)).toBe(100)
  })

  it('passes through valid values', () => {
    expect(clampPixelsPerDay(5)).toBe(5)
  })
})
