import { useState, useEffect } from 'react'
import { Sheet, SheetHeader, SheetTitle } from '@/components/ui/sheet'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select } from '@/components/ui/select'
import { Slider } from '@/components/ui/slider'
import { PhaseDrilldown } from '@/components/phases/PhaseDrilldown'
import { phaseActions } from '@/stores/phaseStore'
import { PhaseCategory, CertaintyLevel, FlexibilityLevel } from '@/types'
import type { Phase, FamilyMember } from '@/types'

interface PhaseEditorProps {
  open: boolean
  onClose: () => void
  scenarioId: string
  phase?: Phase | null
  familyMembers?: FamilyMember[]
}

const defaultValues = {
  name: '',
  category: PhaseCategory.Career as PhaseCategory,
  startDate: '',
  endDate: '',
  certainty: CertaintyLevel.Likely as CertaintyLevel,
  flexibility: FlexibilityLevel.SomewhatFlexible as FlexibilityLevel,
  loadTimeCost: 50,
  emotionalIntensity: 30,
  caregivingHours: 0,
  notes: '',
}

export function PhaseEditor({ open, onClose, scenarioId, phase, familyMembers }: PhaseEditorProps) {
  const [form, setForm] = useState(defaultValues)
  const [view, setView] = useState<'edit' | 'drilldown'>('edit')

  useEffect(() => {
    if (phase) {
      setForm({
        name: phase.name,
        category: phase.category,
        startDate: phase.startDate,
        endDate: phase.endDate,
        certainty: phase.certainty,
        flexibility: phase.flexibility,
        loadTimeCost: phase.loadTimeCost,
        emotionalIntensity: phase.emotionalIntensity,
        caregivingHours: phase.caregivingHours,
        notes: phase.notes,
      })
    } else {
      setForm(defaultValues)
    }
    setView('edit')
  }, [phase, open])

  const set = <K extends keyof typeof defaultValues>(key: K, value: (typeof defaultValues)[K]) =>
    setForm((f) => ({ ...f, [key]: value }))

  const handleSave = async () => {
    if (!form.name || !form.startDate || !form.endDate) return

    if (phase) {
      const updates: Record<string, unknown> = { ...form }
      // If editing an auto-generated phase, clear the flag so it won't be overwritten on regeneration
      if (phase.autoGenerated) {
        updates.autoGenerated = false
      }
      await phaseActions.update(phase.id, updates)
    } else {
      await phaseActions.create({
        ...form,
        scenarioId,
        order: 0,
      })
    }
    onClose()
  }

  const handleDelete = async () => {
    if (phase) {
      await phaseActions.remove(phase.id)
      onClose()
    }
  }

  return (
    <Sheet open={open} onClose={onClose}>
      <SheetHeader>
        <SheetTitle>{phase ? 'Edit Phase' : 'New Phase'}</SheetTitle>
        {phase && (
          <div className="flex gap-1 mt-2">
            <button
              className={`px-3 py-1 text-xs rounded-md ${view === 'edit' ? 'bg-primary text-primary-foreground' : 'bg-secondary text-secondary-foreground'}`}
              onClick={() => setView('edit')}
            >
              Edit
            </button>
            <button
              className={`px-3 py-1 text-xs rounded-md ${view === 'drilldown' ? 'bg-primary text-primary-foreground' : 'bg-secondary text-secondary-foreground'}`}
              onClick={() => setView('drilldown')}
            >
              Drilldown
            </button>
          </div>
        )}
      </SheetHeader>

      {phase?.autoGenerated && view === 'edit' && (
        <div className="mb-4 p-3 bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-md text-xs text-blue-800 dark:text-blue-200">
          Auto-generated from <strong>{familyMembers?.find((m) => m.id === phase.familyMemberId)?.name ?? 'family member'}</strong>'s longevity data. Editing will remove auto-update — this phase won't be regenerated when the family member is updated.
        </div>
      )}

      {phase && view === 'drilldown' ? (
        <PhaseDrilldown phase={phase} scenarioId={scenarioId} />
      ) : (
      <div className="space-y-4">
        <div>
          <Label htmlFor="name">Name</Label>
          <Input
            id="name"
            value={form.name}
            onChange={(e) => set('name', e.target.value)}
            placeholder="e.g., Medical Residency"
          />
        </div>

        <div>
          <Label htmlFor="category">Category</Label>
          <Select
            id="category"
            value={form.category}
            onChange={(e) => set('category', e.target.value as PhaseCategory)}
          >
            {Object.entries(PhaseCategory).map(([key, val]) => (
              <option key={val} value={val}>
                {key}
              </option>
            ))}
          </Select>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div>
            <Label htmlFor="startDate">Start Date</Label>
            <Input
              id="startDate"
              type="date"
              value={form.startDate}
              onChange={(e) => set('startDate', e.target.value)}
            />
          </div>
          <div>
            <Label htmlFor="endDate">End Date</Label>
            <Input
              id="endDate"
              type="date"
              value={form.endDate}
              onChange={(e) => set('endDate', e.target.value)}
            />
          </div>
        </div>

        <div>
          <Label htmlFor="certainty">Certainty</Label>
          <Select
            id="certainty"
            value={form.certainty}
            onChange={(e) => set('certainty', e.target.value as CertaintyLevel)}
          >
            {Object.entries(CertaintyLevel).map(([key, val]) => (
              <option key={val} value={val}>
                {key}
              </option>
            ))}
          </Select>
        </div>

        <div>
          <Label htmlFor="flexibility">Flexibility</Label>
          <Select
            id="flexibility"
            value={form.flexibility}
            onChange={(e) => set('flexibility', e.target.value as FlexibilityLevel)}
          >
            {Object.entries(FlexibilityLevel).map(([key, val]) => (
              <option key={val} value={val}>
                {key}
              </option>
            ))}
          </Select>
        </div>

        <div>
          <Label>Time/Cost Load: {form.loadTimeCost}%</Label>
          <Slider
            min={0}
            max={100}
            value={form.loadTimeCost}
            onChange={(e) => set('loadTimeCost', Number(e.target.value))}
          />
        </div>

        <div>
          <Label>Emotional Intensity: {form.emotionalIntensity}%</Label>
          <Slider
            min={0}
            max={100}
            value={form.emotionalIntensity}
            onChange={(e) => set('emotionalIntensity', Number(e.target.value))}
          />
        </div>

        <div>
          <Label htmlFor="caregivingHours">Caregiving Hours (weekly)</Label>
          <Input
            id="caregivingHours"
            type="number"
            min={0}
            max={168}
            value={form.caregivingHours}
            onChange={(e) => set('caregivingHours', Number(e.target.value))}
          />
        </div>

        <div>
          <Label htmlFor="notes">Notes</Label>
          <textarea
            id="notes"
            className="flex w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring min-h-[80px]"
            value={form.notes}
            onChange={(e) => set('notes', e.target.value)}
          />
        </div>

        <div className="flex gap-2 pt-4">
          <Button onClick={handleSave} className="flex-1">
            {phase ? 'Update' : 'Create'}
          </Button>
          {phase && (
            <Button variant="destructive" onClick={handleDelete}>
              Delete
            </Button>
          )}
          <Button variant="outline" onClick={onClose}>
            Cancel
          </Button>
        </div>
      </div>
      )}
    </Sheet>
  )
}
