/**
 * Family Phase Engine — auto-generates Phase specs from family member data
 *
 * Pure functions that take a FamilyMember + primary person birth date and return
 * phase specifications. These specs are then stored as real Phase objects, so
 * the stress engine automatically picks them up.
 */

import { addYears, formatISO, differenceInYears } from 'date-fns'
import { computeCareNeedsCurve } from '@/engine/longevity-engine'
import { PhaseCategory, CertaintyLevel, FlexibilityLevel } from '@/types'
import type { FamilyMember } from '@/types'

export interface GeneratedPhaseSpec {
  name: string
  category: typeof PhaseCategory.Caregiving | typeof PhaseCategory.Family
  startDate: string // ISO date
  endDate: string   // ISO date
  certainty: CertaintyLevel
  flexibility: FlexibilityLevel
  loadTimeCost: number
  emotionalIntensity: number
  caregivingHours: number
  notes: string
  familyMemberId: string
  autoGenerated: true
}

// Thresholds for care onset from care needs curve
const LIGHT_CARE_THRESHOLD = 15    // >15% probability of light assistance
const MODERATE_CARE_THRESHOLD = 15 // >15% probability of moderate assistance
const FULL_CARE_THRESHOLD = 10     // >10% probability of full care

/**
 * Find the age at which a care probability crosses a threshold
 */
function findOnsetAge(
  curve: ReturnType<typeof computeCareNeedsCurve>,
  field: 'lightAssistance' | 'moderateAssistance' | 'fullCare',
  threshold: number,
): number | null {
  for (const point of curve) {
    if (point[field] > threshold) {
      return point.age
    }
  }
  return null
}

/**
 * Generate caregiving phases for a parent, parent-in-law, or spouse
 */
function generateCarePhases(
  member: FamilyMember,
  caregivingMultiplier: number,
): GeneratedPhaseSpec[] {
  const curve = computeCareNeedsCurve(60, member.sex)
  const phases: GeneratedPhaseSpec[] = []
  const memberBirth = new Date(member.birthDate)
  const relationLabel = member.relationship === 'spouse'
    ? 'Spouse'
    : member.relationship === 'parent-in-law'
      ? 'Parent-in-law'
      : 'Parent'

  const lightOnset = findOnsetAge(curve, 'lightAssistance', LIGHT_CARE_THRESHOLD)
  const moderateOnset = findOnsetAge(curve, 'moderateAssistance', MODERATE_CARE_THRESHOLD)
  const fullOnset = findOnsetAge(curve, 'fullCare', FULL_CARE_THRESHOLD)

  if (lightOnset !== null) {
    const endAge = moderateOnset ?? lightOnset + 10
    phases.push({
      name: `${member.name} — Light Care (${relationLabel})`,
      category: PhaseCategory.Caregiving,
      startDate: formatISO(addYears(memberBirth, lightOnset), { representation: 'date' }),
      endDate: formatISO(addYears(memberBirth, endAge), { representation: 'date' }),
      certainty: CertaintyLevel.Possible,
      flexibility: FlexibilityLevel.Fixed,
      loadTimeCost: 20,
      emotionalIntensity: 30,
      caregivingHours: Math.round(5 * caregivingMultiplier),
      notes: `Auto-generated: light caregiving phase for ${member.name}. ~${Math.round(5 * caregivingMultiplier)} hrs/wk expected.`,
      familyMemberId: member.id,
      autoGenerated: true,
    })
  }

  if (moderateOnset !== null) {
    const endAge = fullOnset ?? moderateOnset + 8
    phases.push({
      name: `${member.name} — Moderate Care (${relationLabel})`,
      category: PhaseCategory.Caregiving,
      startDate: formatISO(addYears(memberBirth, moderateOnset), { representation: 'date' }),
      endDate: formatISO(addYears(memberBirth, endAge), { representation: 'date' }),
      certainty: CertaintyLevel.Possible,
      flexibility: FlexibilityLevel.Fixed,
      loadTimeCost: 45,
      emotionalIntensity: 55,
      caregivingHours: Math.round(15 * caregivingMultiplier),
      notes: `Auto-generated: moderate caregiving phase for ${member.name}. ~${Math.round(15 * caregivingMultiplier)} hrs/wk expected.`,
      familyMemberId: member.id,
      autoGenerated: true,
    })
  }

  if (fullOnset !== null) {
    phases.push({
      name: `${member.name} — Full Care (${relationLabel})`,
      category: PhaseCategory.Caregiving,
      startDate: formatISO(addYears(memberBirth, fullOnset), { representation: 'date' }),
      endDate: formatISO(addYears(memberBirth, fullOnset + 7), { representation: 'date' }),
      certainty: CertaintyLevel.Speculative,
      flexibility: FlexibilityLevel.Fixed,
      loadTimeCost: 70,
      emotionalIntensity: 75,
      caregivingHours: Math.round(30 * caregivingMultiplier),
      notes: `Auto-generated: full-time caregiving phase for ${member.name}. ~${Math.round(30 * caregivingMultiplier)} hrs/wk expected.`,
      familyMemberId: member.id,
      autoGenerated: true,
    })
  }

  return phases
}

/** Child development phase definitions */
const CHILD_PHASES: {
  name: string
  startAge: number
  endAge: number
  loadTimeCost: number
  emotionalIntensity: number
  caregivingHours: number
}[] = [
  { name: 'Infant', startAge: 0, endAge: 1, loadTimeCost: 85, emotionalIntensity: 60, caregivingHours: 50 },
  { name: 'Toddler', startAge: 1, endAge: 3, loadTimeCost: 75, emotionalIntensity: 50, caregivingHours: 40 },
  { name: 'Preschool', startAge: 3, endAge: 5, loadTimeCost: 55, emotionalIntensity: 35, caregivingHours: 30 },
  { name: 'Elementary', startAge: 5, endAge: 10, loadTimeCost: 40, emotionalIntensity: 25, caregivingHours: 20 },
  { name: 'Middle School', startAge: 11, endAge: 13, loadTimeCost: 30, emotionalIntensity: 35, caregivingHours: 10 },
  { name: 'High School', startAge: 14, endAge: 18, loadTimeCost: 25, emotionalIntensity: 30, caregivingHours: 5 },
]

/**
 * Generate development phases for a child
 */
function generateChildPhases(member: FamilyMember): GeneratedPhaseSpec[] {
  const childBirth = new Date(member.birthDate)
  const now = new Date()
  const currentChildAge = differenceInYears(now, childBirth)

  return CHILD_PHASES
    .filter((p) => p.endAge > currentChildAge) // Skip past phases
    .map((p) => ({
      name: `${member.name} — ${p.name}`,
      category: PhaseCategory.Family as typeof PhaseCategory.Family,
      startDate: formatISO(
        p.startAge <= currentChildAge ? now : addYears(childBirth, p.startAge),
        { representation: 'date' },
      ),
      endDate: formatISO(addYears(childBirth, p.endAge), { representation: 'date' }),
      certainty: CertaintyLevel.Likely as CertaintyLevel,
      flexibility: FlexibilityLevel.Fixed as FlexibilityLevel,
      loadTimeCost: p.loadTimeCost,
      emotionalIntensity: p.emotionalIntensity,
      caregivingHours: p.caregivingHours,
      notes: `Auto-generated: ${p.name.toLowerCase()} phase for ${member.name}.`,
      familyMemberId: member.id,
      autoGenerated: true as const,
    }))
}

/**
 * Main dispatch: generate phases for any family member type
 */
export function generateFamilyPhases(
  member: FamilyMember,
  _primaryBirthDate: string,
): GeneratedPhaseSpec[] {
  switch (member.relationship) {
    case 'parent':
    case 'parent-in-law':
      return generateCarePhases(member, 1.0)
    case 'spouse':
      return generateCarePhases(member, 0.7)
    case 'child':
      return generateChildPhases(member)
    case 'sibling':
      return [] // Siblings: for LongevityView comparison only
    default:
      return []
  }
}
