// ── Enums as const objects (erasableSyntaxOnly compatible) ──

export const PhaseCategory = {
  Career: 'career',
  Education: 'education',
  Family: 'family',
  Caregiving: 'caregiving',
  Health: 'health',
  Housing: 'housing',
  Financial: 'financial',
  Personal: 'personal',
  Relationship: 'relationship',
  BiologicRhythms: 'biologic-rhythms',
} as const
export type PhaseCategory = (typeof PhaseCategory)[keyof typeof PhaseCategory]

export const CertaintyLevel = {
  Confirmed: 'confirmed',
  Likely: 'likely',
  Possible: 'possible',
  Speculative: 'speculative',
} as const
export type CertaintyLevel = (typeof CertaintyLevel)[keyof typeof CertaintyLevel]

export const PresentationMode = {
  Strategic: 'strategic',
  Narrative: 'narrative',
  Shared: 'shared',
} as const
export type PresentationMode = (typeof PresentationMode)[keyof typeof PresentationMode]

export const AccessibilityMode = {
  Default: 'default',
  TextOnly: 'text-only',
  NumericOnly: 'numeric-only',
  IconOnly: 'icon-only',
} as const
export type AccessibilityMode = (typeof AccessibilityMode)[keyof typeof AccessibilityMode]

export const ZoomLevel = {
  Decade: 'decade',
  Year: 'year',
  Month: 'month',
  Week: 'week',
} as const
export type ZoomLevel = (typeof ZoomLevel)[keyof typeof ZoomLevel]

export const DebtStrategy = {
  MinimumPayment: 'minimum-payment',
  Snowball: 'snowball',
  Avalanche: 'avalanche',
  FixedPayment: 'fixed-payment',
} as const
export type DebtStrategy = (typeof DebtStrategy)[keyof typeof DebtStrategy]

export const FlexibilityLevel = {
  Fixed: 'fixed',
  SomewhatFlexible: 'somewhat-flexible',
  VeryFlexible: 'very-flexible',
} as const
export type FlexibilityLevel = (typeof FlexibilityLevel)[keyof typeof FlexibilityLevel]

export type Sex = 'male' | 'female'

export const Relationship = {
  Parent: 'parent',
  ParentInLaw: 'parent-in-law',
  Spouse: 'spouse',
  Child: 'child',
  Sibling: 'sibling',
} as const
export type Relationship = (typeof Relationship)[keyof typeof Relationship]

export interface FamilyMember {
  id: string
  personId: string
  name: string
  birthDate: string // ISO date
  sex: Sex
  relationship: Relationship
  createdAt: string
  updatedAt: string
}

// ── Core Data Models ──

export interface Person {
  id: string
  name: string
  birthDate: string // ISO date
  sex?: Sex
  createdAt: string
  updatedAt: string
}

export interface Household {
  id: string
  name: string
  personIds: string[]
  createdAt: string
}

export interface Scenario {
  id: string
  personId: string
  name: string
  description: string
  isBaseline: boolean
  createdAt: string
  updatedAt: string
}

export interface Phase {
  id: string
  scenarioId: string
  name: string
  category: PhaseCategory
  startDate: string // ISO date
  endDate: string   // ISO date
  certainty: CertaintyLevel
  flexibility: FlexibilityLevel
  loadTimeCost: number    // 0-100: how much time this phase consumes
  emotionalIntensity: number // 0-100
  caregivingHours: number // weekly hours (0 if none)
  notes: string
  templateId?: string
  familyMemberId?: string
  autoGenerated?: boolean
  order: number
  createdAt: string
  updatedAt: string
}

export interface Account {
  id: string
  scenarioId: string
  name: string
  type: 'checking' | 'savings' | 'investment' | 'retirement' | 'debt'
  balance: number
  interestRate: number // annual %
  createdAt: string
}

export interface DebtPlan {
  id: string
  scenarioId: string
  name: string
  principalBalance: number
  annualInterestRate: number  // %
  minimumPayment: number      // monthly minimum
  monthlyPayment: number      // actual monthly payment (>= minimum)
  strategy: DebtStrategy
  startDate: string           // ISO date — when payoff begins
  extraPayment: number        // additional monthly amount above minimum
  createdAt: string
}

export interface DebtPayoffMonth {
  month: string   // YYYY-MM
  debtId: string
  debtName: string
  startingBalance: number
  payment: number
  interestCharged: number
  principalPaid: number
  endingBalance: number
  isPaidOff: boolean
}

export interface DebtPayoffSummary {
  debtId: string
  debtName: string
  originalBalance: number
  totalInterestPaid: number
  totalPaid: number
  monthsToPayoff: number
  payoffDate: string
}

export interface SavingsGoal {
  id: string
  scenarioId: string
  name: string
  targetAmount: number
  currentBalance: number
  monthlyContribution: number
  annualReturnRate: number   // expected % return
  startDate: string
  targetDate: string         // when you want to reach the goal
  type: 'emergency' | 'retirement' | 'education' | 'house' | 'custom'
  createdAt: string
}

export interface SavingsProjectionMonth {
  month: string
  goalId: string
  goalName: string
  balance: number
  contribution: number
  growth: number
  percentComplete: number
}

export interface IncomeStream {
  id: string
  scenarioId: string
  name: string
  monthlyAmount: number
  startDate: string
  endDate: string
  annualGrowthRate: number // %
  certainty: CertaintyLevel
  phaseId?: string // optional link to a phase
  createdAt: string
}

export interface ExpenseRule {
  id: string
  scenarioId: string
  name: string
  monthlyAmount: number
  startDate: string
  endDate: string
  annualInflationRate: number // %
  category: string
  isRequired: boolean
  phaseId?: string
  createdAt: string
}

export interface Assumption {
  id: string
  scenarioId: string
  key: string
  value: number
  unit: string
  description: string
}

// ── Computed / Projection types ──

export interface MonthlyProjection {
  month: string // YYYY-MM
  totalIncome: number
  totalExpenses: number
  netCashflow: number
  netWorth: number
  netWorthLow: number  // uncertainty band low
  netWorthHigh: number // uncertainty band high
}

export interface StressScore {
  month: string
  composite: number // 0-100
  freeTime: number
  financialSurplus: number
  overlapCount: number
  caregivingLoad: number
  sleepProxy: number
  emotionalLoad: number
}

export interface ScenarioDiff {
  netWorthAtRetirement: { a: number; b: number; delta: number }
  peakStress: { a: number; b: number; delta: number }
  worstMonth: { a: string; b: string }
  redZoneMonths: { a: number; b: number; delta: number }
  freeTimeMinimum: { a: number; b: number; delta: number }
}

// ── Template types ──

export interface TemplatePhase {
  name: string
  category: PhaseCategory
  offsetMonths: number // from template start
  durationMonths: number
  certainty: CertaintyLevel
  flexibility: FlexibilityLevel
  loadTimeCost: number
  emotionalIntensity: number
  caregivingHours: number
  notes: string
}

export interface Template {
  id: string
  name: string
  description: string
  group: 'career' | 'children' | 'caregiving'
  phases: TemplatePhase[]
}

// ── UI State types ──

export interface ViewportState {
  offsetX: number
  offsetY: number
  pixelsPerDay: number
}
