import { v4 as uuid } from 'uuid'
import { db } from '@/db/database'
import { phaseActions } from '@/stores/phaseStore'
import { generateFamilyPhases } from '@/engine/family-phase-engine'
import type { FamilyMember, Sex, Relationship } from '@/types'

export const familyMemberActions = {
  async create(
    personId: string,
    name: string,
    birthDate: string,
    sex: Sex,
    relationship: Relationship,
    scenarioId: string,
    primaryBirthDate: string,
  ): Promise<FamilyMember> {
    const now = new Date().toISOString()
    const member: FamilyMember = {
      id: uuid(),
      personId,
      name,
      birthDate,
      sex,
      relationship,
      createdAt: now,
      updatedAt: now,
    }

    await db.familyMembers.add(member)

    // Auto-generate phases
    const specs = generateFamilyPhases(member, primaryBirthDate)
    const existingCount = await db.phases.where('scenarioId').equals(scenarioId).count()

    for (let i = 0; i < specs.length; i++) {
      await phaseActions.create({
        ...specs[i],
        scenarioId,
        order: existingCount + i,
      })
    }

    return member
  },

  async update(
    id: string,
    updates: Partial<Pick<FamilyMember, 'name' | 'birthDate' | 'sex' | 'relationship'>>,
    scenarioId: string,
    primaryBirthDate: string,
  ) {
    await db.familyMembers.update(id, { ...updates, updatedAt: new Date().toISOString() })

    // If birthDate or sex changed, regenerate phases
    if (updates.birthDate !== undefined || updates.sex !== undefined || updates.relationship !== undefined) {
      const member = await db.familyMembers.get(id)
      if (!member) return

      // Delete existing auto-generated phases for this member
      const autoPhases = await db.phases
        .where('familyMemberId')
        .equals(id)
        .toArray()
      const autoIds = autoPhases.filter((p) => p.autoGenerated).map((p) => p.id)
      if (autoIds.length > 0) {
        await db.phases.bulkDelete(autoIds)
      }

      // Regenerate
      const specs = generateFamilyPhases(member, primaryBirthDate)
      const existingCount = await db.phases.where('scenarioId').equals(scenarioId).count()

      for (let i = 0; i < specs.length; i++) {
        await phaseActions.create({
          ...specs[i],
          scenarioId,
          order: existingCount + i,
        })
      }
    }
  },

  async remove(id: string) {
    await db.transaction('rw', [db.familyMembers, db.phases], async () => {
      // Delete auto-generated phases for this member
      const autoPhases = await db.phases
        .where('familyMemberId')
        .equals(id)
        .toArray()
      const autoIds = autoPhases.filter((p) => p.autoGenerated).map((p) => p.id)
      if (autoIds.length > 0) {
        await db.phases.bulkDelete(autoIds)
      }

      await db.familyMembers.delete(id)
    })
  },
}
